import type { Metadata } from "next";
import "./globals.css";

import { ReactNode } from "react";
import { Providers } from "./providers";
import Navbar from "@/components/Home/Navbar";
export const metadata: Metadata = {
  title: "DEFI PROTOCOL",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: ReactNode
}
) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
          <Navbar />
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
